export type ESGLinkItem = {
  href: string;
  label: string;
};

export type ESGCardItem = {
  title: string;
  description: string;
};

export type ESGServiceConfig = {
  slug: string;
  title: string;
  description: string;
  heroAlt: string;
  introHeading: string;
  introParagraphs: string[];
  introLinks: ESGLinkItem[];
  coverageIntro: string;
  deliverables: ESGCardItem[];
  bestFitIntro: string;
  bestFit: ESGCardItem[];
  workflowIntro: string;
  workflow: ESGCardItem[];
  serviceTypes: string[];
  faq: ESGCardItem[];
};

export const esgServiceConfigs = {
  net_zero_and_decarbonisation: {
    slug: "net-zero-and-decarbonisation",
    title: "Net zero and decarbonisation advisory",
    description: "Net zero and decarbonisation advisory for organisations that need a credible reduction roadmap, target-setting discipline, and measurable delivery across operations and the value chain.",
    heroAlt: "Net zero and decarbonisation advisory for climate transition planning",
    introHeading: "Move from emissions data to a practical reduction plan",
    introParagraphs: [
      "Many organisations can calculate emissions, but far fewer can turn that baseline into a practical decarbonisation plan that leadership can fund, sequence and govern.",
      "We help teams define the reduction pathway, evaluate the highest-impact levers, align targets to operating reality, and build the governance needed to keep delivery moving after the strategy workshop ends.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/carbon-accounting", label: "Carbon accounting" },
      { href: "/services/esg-advisory/climate-risk", label: "Climate risk" },
      { href: "/regulatory-hub", label: "Regulatory hub" },
    ],
    coverageIntro: "We support the planning, prioritisation and operating model needed to move climate ambition into execution.",
    deliverables: [
      { title: "Baseline and hotspot review", description: "Assess the existing emissions baseline, major sources, and the quality of underlying assumptions before reduction planning begins." },
      { title: "Target and ambition setting", description: "Clarify reduction ambition, timing and governance so targets are credible and measurable rather than purely symbolic." },
      { title: "Decarbonisation levers", description: "Identify reduction opportunities across energy, procurement, logistics, operations and product or service design." },
      { title: "Scenario and roadmap design", description: "Sequence initiatives into a roadmap with dependencies, owners and practical timing." },
      { title: "Business case support", description: "Frame reduction opportunities in terms leadership can evaluate, including cost, operational feasibility, and risk." },
      { title: "Governance and tracking", description: "Define cadence, controls and reporting so progress can be monitored and decisions can be made with confidence." },
    ],
    bestFitIntro: "This work is most useful when climate action needs to move from broad intent to a governed delivery plan.",
    bestFit: [
      { title: "After the first carbon baseline", description: "You have emissions numbers but no agreed reduction pathway or ownership model behind them." },
      { title: "Before target-setting", description: "Leadership wants a credible view of what is achievable before committing publicly to targets or timelines." },
      { title: "When action has stalled", description: "Multiple ideas exist across teams, but there is no prioritised roadmap, funding logic, or execution cadence." },
    ],
    workflowIntro: "We structure the work so climate planning becomes an operating model, not a one-off slide deck.",
    workflow: [
      { title: "Diagnose", description: "Review current emissions, available data, previous commitments, and the constraints that matter most." },
      { title: "Prioritise", description: "Assess reduction levers by impact, feasibility, timing and organisational readiness." },
      { title: "Design", description: "Build a roadmap, target framework, ownership model, and decision cadence." },
      { title: "Embed", description: "Support stakeholder alignment, tracking and governance so the roadmap can be used in practice." },
    ],
    serviceTypes: [
      "Net zero roadmap development",
      "Decarbonisation strategy",
      "Climate target-setting support",
      "Reduction lever prioritisation",
      "Transition planning governance",
      "Climate programme operating model",
    ],
    faq: [
      { title: "What is included in net zero and decarbonisation advisory?", description: "We assess the baseline, identify major emissions hotspots, define reduction levers, structure the roadmap, and support target-setting and governance so delivery can continue after the strategy phase." },
      { title: "How is this different from carbon accounting?", description: "Carbon accounting establishes the emissions baseline. Net zero and decarbonisation advisory uses that baseline to prioritise reduction actions, targets, sequencing and governance." },
      { title: "Do you support science-based target planning?", description: "Yes. We help organisations evaluate ambition, data readiness, and reduction feasibility so targets are grounded in operational reality." },
      { title: "Can you help prioritise initiatives across functions?", description: "Yes. We compare initiatives across operations, procurement, logistics, facilities and other areas so leadership can focus on the levers with the strongest combination of impact and practicality." },
      { title: "Do you implement the roadmap too?", description: "Yes. Our model is advisory plus implementation. We can help define governance, working rhythms, reporting and documentation so the roadmap is used rather than archived." },
      { title: "Is this only for large enterprises?", description: "No. It is useful for mid-market and enterprise organisations alike when climate action needs clearer structure, ownership and decision support." },
      { title: "Do you provide assurance or certification?", description: "No. We do not provide statutory audit, assurance or certification." },
    ],
  },
  climate_risk: {
    slug: "climate-risk",
    title: "Climate risk advisory",
    description: "Climate risk advisory for organisations that need clearer visibility into physical and transition risks, stronger disclosure inputs, and a practical governance model for climate resilience.",
    heroAlt: "Climate risk advisory for physical and transition risk assessment",
    introHeading: "Understand the climate risks that can affect operations, supply chains, and disclosure quality",
    introParagraphs: [
      "Climate risk is no longer only a reporting issue. It affects assets, suppliers, financing conversations, resilience planning, and the credibility of climate disclosures.",
      "We help organisations assess physical and transition risks, structure the analysis for leadership decision-making, and connect the outputs to reporting obligations and operational priorities.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/net-zero-and-decarbonisation", label: "Net zero and decarbonisation" },
      { href: "/services/esg-advisory/cdp-reporting", label: "CDP reporting" },
      { href: "/services/esg-advisory/uk-secr-srs-reporting", label: "UK SECR and SRS reporting" },
    ],
    coverageIntro: "We focus on risk clarity, reporting usefulness, and decision-ready outputs rather than generic climate commentary.",
    deliverables: [
      { title: "Risk boundaries and context", description: "Define relevant sites, business units, suppliers and value chain elements so the assessment is scoped properly." },
      { title: "Physical and transition risk identification", description: "Map the climate risks and opportunities most relevant to your sector, geography and operating model." },
      { title: "Scenario-based assessment", description: "Use structured scenarios and time horizons to assess how risk exposure may evolve." },
      { title: "Impact evaluation", description: "Translate climate risks into operational, financial, reputational and governance implications." },
      { title: "Disclosure support", description: "Shape the outputs so they can support TCFD-aligned, CDP, CSRD or other climate-related reporting." },
      { title: "Resilience roadmap", description: "Define practical mitigation actions, ownership and next-step priorities rather than stopping at the assessment report." },
    ],
    bestFitIntro: "This service is most valuable when climate risk needs to be understood as a business issue, not only a disclosure exercise.",
    bestFit: [
      { title: "Before climate disclosures", description: "You need clearer risk analysis before producing or strengthening climate-related reporting." },
      { title: "For operational resilience", description: "Leadership wants visibility into how climate events or transition pressures could affect assets, suppliers or continuity." },
      { title: "When reporting feels generic", description: "Your current climate narrative is too broad and lacks the analysis needed to support board-level decisions." },
    ],
    workflowIntro: "We combine structured assessment with governance so the outputs can support both reporting and decision-making.",
    workflow: [
      { title: "Scope", description: "Define organisational boundaries, relevant geographies, and the business questions the assessment needs to answer." },
      { title: "Assess", description: "Identify physical and transition risks, review scenarios, and evaluate likely impacts." },
      { title: "Translate", description: "Convert the analysis into risk registers, priorities and disclosure-ready insights." },
      { title: "Govern", description: "Clarify owners, review cadence, and how the climate risk view will be maintained over time." },
    ],
    serviceTypes: [
      "Climate risk assessment",
      "Physical and transition risk analysis",
      "Scenario analysis support",
      "Climate disclosure support",
      "Resilience planning",
      "Climate governance advisory",
    ],
    faq: [
      { title: "What does climate risk advisory include?", description: "It includes scope setting, risk identification, scenario-based analysis, impact evaluation, disclosure support, and practical recommendations for resilience and governance." },
      { title: "Do you cover both physical and transition risks?", description: "Yes. We assess acute and chronic physical risks as well as regulatory, market, technology and reputational transition risks." },
      { title: "Can this support disclosure requirements?", description: "Yes. The outputs can support climate-related disclosures where a clearer risk narrative and supporting analysis are needed." },
      { title: "Do you do detailed modelling?", description: "We can support structured assessment and prioritisation. Where very specialised modelling is needed, we frame requirements and integrate the outputs into the governance and reporting process." },
      { title: "How is this linked to net zero planning?", description: "Climate risk and decarbonisation are connected. Risk analysis helps clarify exposure and resilience priorities, while decarbonisation planning focuses on reduction pathways and transition action." },
      { title: "Who usually owns this internally?", description: "Ownership often sits across sustainability, risk, finance, operations and strategy. We help define a workable cross-functional model rather than assuming a single owner can handle everything." },
      { title: "Do you provide assurance?", description: "No. We do not provide statutory audit or assurance." },
    ],
  },
  cdp_reporting: {
    slug: "cdp-reporting",
    title: "CDP reporting advisory",
    description: "CDP reporting advisory for organisations that need stronger climate disclosure, better evidence quality, and a more structured response process across data, governance and narrative.",
    heroAlt: "CDP reporting advisory for disclosure preparation and governance",
    introHeading: "Build a CDP response that is structured, credible and easier to repeat",
    introParagraphs: [
      "CDP responses often become stressful because climate data, governance evidence, and narrative inputs sit across too many teams and systems.",
      "We help organisations prepare the response process, improve evidence quality, close priority gaps, and shape a submission that is clearer for reviewers and more manageable for internal teams.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/carbon-accounting", label: "Carbon accounting" },
      { href: "/services/esg-advisory/climate-risk", label: "Climate risk" },
      { href: "/services/esg-advisory/net-zero-and-decarbonisation", label: "Net zero and decarbonisation" },
    ],
    coverageIntro: "We focus on submission quality, process discipline, and the evidence base behind the response.",
    deliverables: [
      { title: "Response readiness review", description: "Assess the current state of climate data, governance, targets and documentation before drafting begins." },
      { title: "Question-by-question mapping", description: "Map data sources, owners, evidence and narrative inputs to the relevant response areas." },
      { title: "Gap identification", description: "Highlight missing governance elements, weak evidence areas, and opportunities to strengthen the submission." },
      { title: "Drafting and review support", description: "Support clearer response drafting, consistency checks, and final review before submission." },
      { title: "Data and evidence pack", description: "Organise supporting information so the response is easier to defend internally and repeat next cycle." },
      { title: "Improvement roadmap", description: "Prioritise the changes that will strengthen future responses and broader climate governance." },
    ],
    bestFitIntro: "This service is most useful when the CDP response needs more than last-minute drafting help.",
    bestFit: [
      { title: "First-time response teams", description: "You need structure, interpretation support, and a realistic process across multiple contributors." },
      { title: "Repeat respondents", description: "You submitted before, but the response process was fragmented and the output did not reflect the quality of your actual work." },
      { title: "Climate disclosure upgrades", description: "You want CDP to reflect stronger governance, better carbon data, and clearer climate strategy." },
    ],
    workflowIntro: "We help teams make the response more repeatable each cycle, not just complete it once.",
    workflow: [
      { title: "Review", description: "Assess current climate data, governance, prior disclosures, and likely response pressure points." },
      { title: "Map", description: "Assign owners, evidence sources, and drafting responsibilities across the questionnaire." },
      { title: "Strengthen", description: "Close priority gaps in narrative clarity, supporting evidence, and consistency." },
      { title: "Submit", description: "Support final review and create a post-cycle improvement plan." },
    ],
    serviceTypes: [
      "CDP response support",
      "Climate disclosure advisory",
      "Questionnaire mapping",
      "Evidence pack preparation",
      "Submission review",
      "Disclosure improvement roadmap",
    ],
    faq: [
      { title: "What does CDP reporting advisory include?", description: "It includes readiness review, data and evidence mapping, drafting support, consistency review, and a roadmap for improving future responses." },
      { title: "Can you help first-time CDP respondents?", description: "Yes. We help clarify what is being asked, what evidence is needed, and how to organise contributors and timelines." },
      { title: "Do you only help with writing?", description: "No. The value usually comes from better process design, clearer ownership, stronger evidence, and improved response quality, not only drafting support." },
      { title: "How does this connect to carbon accounting?", description: "CDP often depends on reliable emissions data, target-setting, and climate governance. Carbon accounting can be a parallel or prerequisite workstream when the baseline is not strong enough." },
      { title: "Can you review an existing draft?", description: "Yes. We can review current drafts, identify weak areas, and recommend improvements before submission." },
      { title: "Will this also improve other climate disclosures?", description: "Often yes. Better governance, data discipline, and narrative clarity can support other climate and ESG reporting needs as well." },
      { title: "Do you provide scoring guarantees?", description: "No. We do not guarantee scores. We focus on strengthening the quality, coherence and defensibility of the response." },
    ],
  },
  product_sustainability: {
    slug: "product-sustainability",
    title: "Product sustainability advisory",
    description: "Product sustainability advisory for organisations that need clearer insight into product impacts, stronger evidence for customers, and a more structured basis for product claims and improvement priorities.",
    heroAlt: "Product sustainability advisory for product impact assessment and improvement",
    introHeading: "Clarify product impacts before customers or regulators force the question",
    introParagraphs: [
      "Product sustainability becomes difficult when environmental and social claims move faster than the underlying evidence, data and cross-functional coordination.",
      "We help organisations understand product-level sustainability issues, structure the data and assumptions behind them, and build a more defensible basis for decisions, customer conversations, and future improvements.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/supplier-engagement", label: "Supplier engagement" },
      { href: "/services/esg-advisory/cdp-reporting", label: "CDP reporting" },
      { href: "/services/esg-advisory/net-zero-and-decarbonisation", label: "Net zero and decarbonisation" },
    ],
    coverageIntro: "We support product-level sustainability work where evidence quality and commercial relevance both matter.",
    deliverables: [
      { title: "Product impact scoping", description: "Clarify which products, categories or claims need attention first and what questions the analysis must answer." },
      { title: "Data and assumption mapping", description: "Identify the supplier, materials, process, packaging, logistics or usage data needed to build a usable view." },
      { title: "Impact analysis support", description: "Assess product-level sustainability considerations in a structured way, with documented assumptions and boundaries." },
      { title: "Claim and evidence review", description: "Review current product sustainability claims, supporting data, and areas where evidence needs to be strengthened." },
      { title: "Improvement prioritisation", description: "Identify where redesign, sourcing, packaging, process or supplier changes are most worth exploring." },
      { title: "Governance for repeatability", description: "Define who owns updates, reviews, documentation and change control as products or claims evolve." },
    ],
    bestFitIntro: "This work is especially useful when product-level sustainability questions are growing faster than internal readiness.",
    bestFit: [
      { title: "Customer scrutiny is increasing", description: "Buyers or commercial teams need more credible answers on product impacts, sourcing or sustainability claims." },
      { title: "Claims need stronger evidence", description: "Marketing, product and sustainability teams need a better basis for what can and cannot be said." },
      { title: "Improvement efforts are scattered", description: "You need a structured view of where product changes could have the strongest sustainability effect." },
    ],
    workflowIntro: "We connect product, procurement, operations and sustainability teams around a usable evidence base.",
    workflow: [
      { title: "Prioritise", description: "Select the products, categories or claims where better evidence matters most." },
      { title: "Map", description: "Define the data, assumptions and contributors needed for the analysis." },
      { title: "Assess", description: "Review impacts, evidence strength, and commercial relevance." },
      { title: "Improve", description: "Set governance and priorities for product-level sustainability improvements." },
    ],
    serviceTypes: [
      "Product sustainability advisory",
      "Product impact assessment support",
      "Sustainability claims review",
      "Product data mapping",
      "Improvement prioritisation",
      "Product sustainability governance",
    ],
    faq: [
      { title: "What is product sustainability advisory?", description: "It is structured support to understand product-level sustainability impacts, strengthen evidence behind claims, and prioritise improvement actions across product, procurement, operations and sustainability teams." },
      { title: "Do you do full life-cycle assessments?", description: "We can support scoped product impact work and help define where deeper specialist analysis is needed. Our role focuses on decision usefulness, governance and integration into the wider operating model." },
      { title: "Can this help with customer requests?", description: "Yes. It is often used when sales, procurement or customer teams need more credible and consistent product sustainability information." },
      { title: "Is this only for manufacturers?", description: "No. It is relevant for manufacturers, retailers, consumer brands, and other organisations where product design, sourcing, packaging or claims are under scrutiny." },
      { title: "How does supplier data fit in?", description: "Supplier data is often critical. We help define the evidence expectations, data collection approach, and governance needed to make the product view more reliable over time." },
      { title: "Can you review sustainability claims?", description: "Yes. We can review the evidence base behind current claims and highlight where language, assumptions or documentation need to be tightened." },
      { title: "Do you certify products?", description: "No. We do not provide certification or assurance." },
    ],
  },
  b_corp_certification: {
    slug: "b-corp-certification",
    title: "B Corp certification advisory",
    description: "B Corp certification advisory for organisations that need a structured readiness plan, stronger evidence, and practical coordination across policy, data and operating model changes.",
    heroAlt: "B Corp certification advisory for readiness and evidence development",
    introHeading: "Prepare for B Corp with clearer ownership, stronger evidence, and fewer surprises",
    introParagraphs: [
      "B Corp work can become sprawling because it touches governance, people, environment, community and customer-related practices at the same time.",
      "We help organisations turn the certification journey into a practical programme. That means assessing the current position, prioritising improvements, coordinating evidence, and structuring the operating rhythm needed to move the process forward.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/ecovadis-readiness", label: "EcoVadis readiness" },
      { href: "/services/esg-advisory/sustainability-strategy", label: "Sustainability strategy" },
      { href: "/services/esg-advisory/sustainability-training", label: "Sustainability training" },
    ],
    coverageIntro: "We focus on readiness, evidence and cross-functional execution rather than treating certification as a form-filling exercise.",
    deliverables: [
      { title: "Readiness assessment", description: "Review the current position against likely certification requirements and identify the strongest gaps." },
      { title: "Improvement roadmap", description: "Prioritise the policy, process, governance and documentation changes needed to improve readiness." },
      { title: "Evidence coordination", description: "Map evidence requirements, owners and dependencies across functions." },
      { title: "Submission preparation", description: "Support structured completion, review and refinement of the assessment process." },
      { title: "Governance design", description: "Set decision points, ownership and working cadence so the process does not drift." },
      { title: "Post-assessment planning", description: "Translate the work into a broader operating discipline that remains useful beyond certification." },
    ],
    bestFitIntro: "This service is valuable when B Corp interest is real, but internal readiness is uneven.",
    bestFit: [
      { title: "Early-stage preparation", description: "Leadership wants to understand how much work sits between current state and certification readiness." },
      { title: "Cross-functional coordination gaps", description: "Different functions own relevant policies and evidence, but nobody has an integrated plan." },
      { title: "Certification with substance", description: "You want the process to improve governance and accountability, not just produce a badge." },
    ],
    workflowIntro: "We help teams break the journey into practical workstreams and clearer ownership.",
    workflow: [
      { title: "Assess", description: "Review current maturity, likely evidence needs, and the areas that need the most attention." },
      { title: "Plan", description: "Create a staged roadmap across governance, people, environment and documentation." },
      { title: "Coordinate", description: "Support teams in gathering evidence, refining policies, and progressing actions." },
      { title: "Prepare", description: "Review submission readiness and define the next cycle of improvements." },
    ],
    serviceTypes: [
      "B Corp readiness assessment",
      "B Corp improvement roadmap",
      "Evidence mapping",
      "Certification preparation",
      "Cross-functional sustainability programme support",
      "Governance advisory",
    ],
    faq: [
      { title: "What does B Corp certification advisory include?", description: "It includes readiness assessment, improvement planning, evidence coordination, submission support, and governance design so the journey is practical and better structured." },
      { title: "Can you help if we are only exploring B Corp?", description: "Yes. A readiness review is often the best starting point because it clarifies the likely effort, the main gaps, and whether certification fits your current priorities." },
      { title: "Is this mainly a documentation exercise?", description: "No. Documentation matters, but meaningful progress usually depends on policy, process and governance changes as well." },
      { title: "How does this differ from EcoVadis support?", description: "EcoVadis is a buyer-driven assessment with a strong documentation and scoring logic. B Corp is a broader certification journey with a wider operating model and governance impact." },
      { title: "Can this improve broader sustainability maturity too?", description: "Yes. Many of the improvements around policy quality, evidence, accountability and governance remain useful beyond the certification process." },
      { title: "Do you handle the whole process for us?", description: "We support the process end to end, but the work still needs to reflect your organisation's real practices, evidence and decisions." },
      { title: "Do you provide certification?", description: "No. We do not certify organisations." },
    ],
  },
  supplier_engagement: {
    slug: "supplier-engagement",
    title: "Supplier engagement advisory",
    description: "Supplier engagement advisory for organisations that need better sustainability data from the supply base, stronger procurement governance, and a more practical way to improve value chain readiness.",
    heroAlt: "Supplier engagement advisory for procurement and value chain sustainability",
    introHeading: "Strengthen supply chain sustainability with a clearer operating model",
    introParagraphs: [
      "Many ESG programmes stall at the supplier layer. The requirements are rising, but procurement teams often lack the structure, data process, and engagement model needed to get usable information back from suppliers.",
      "We help organisations design supplier engagement approaches that are more practical for procurement teams and more effective for value chain data, risk visibility, and buyer expectations.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/ecovadis-readiness", label: "EcoVadis readiness" },
      { href: "/services/esg-advisory/product-sustainability", label: "Product sustainability" },
      { href: "/services/esg-advisory/rfp-tender-support", label: "RFP and tender support" },
    ],
    coverageIntro: "We focus on supplier engagement that improves information quality, governance and commercial usefulness.",
    deliverables: [
      { title: "Supplier segmentation", description: "Prioritise suppliers by spend, risk, category or strategic relevance so the engagement model is proportionate." },
      { title: "Questionnaire and evidence design", description: "Define the data requests, evidence expectations, and supporting materials needed from suppliers." },
      { title: "Procurement operating model", description: "Clarify who owns outreach, follow-up, escalation, review and decision-making." },
      { title: "Supplier communication approach", description: "Create a more practical engagement rhythm, from onboarding to improvement conversations." },
      { title: "Data quality and review process", description: "Set rules for reviewing responses, resolving gaps, and escalating critical issues." },
      { title: "Improvement roadmap", description: "Turn supplier findings into procurement actions, category plans, and longer-term value chain improvements." },
    ],
    bestFitIntro: "This service is most useful when sustainability expectations have reached procurement, but the process is not yet strong enough.",
    bestFit: [
      { title: "Value chain data is weak", description: "You need better supplier inputs for reporting, customer requests, or product-level analysis." },
      { title: "Procurement is under pressure", description: "Buyers, customers or regulations are asking more of the supply base than the current process can support." },
      { title: "Follow-up is inconsistent", description: "Suppliers are contacted, but responses are hard to compare, verify or convert into action." },
    ],
    workflowIntro: "We help turn supplier sustainability work into an operating rhythm rather than a periodic scramble.",
    workflow: [
      { title: "Prioritise", description: "Segment suppliers and define what information matters most." },
      { title: "Design", description: "Set the data request, evidence expectations, communication model, and review rules." },
      { title: "Engage", description: "Support rollout, follow-up, and issue handling across the supplier base." },
      { title: "Improve", description: "Translate outputs into procurement governance and supplier improvement actions." },
    ],
    serviceTypes: [
      "Supplier engagement advisory",
      "Sustainable procurement support",
      "Supplier data collection design",
      "Procurement governance",
      "Value chain readiness support",
      "Supplier improvement roadmap",
    ],
    faq: [
      { title: "What is supplier engagement advisory?", description: "It is support to design and run a more effective sustainability engagement model with suppliers, including segmentation, data requests, evidence expectations, follow-up, and governance." },
      { title: "Is this mainly for procurement teams?", description: "Procurement is usually central, but sustainability, operations, quality and product teams are often involved too. We help define a workable cross-functional model." },
      { title: "Can this support reporting requirements?", description: "Yes. Better supplier engagement often improves value chain data quality for reporting, customer requests, and product sustainability work." },
      { title: "Do you help with supplier questionnaires?", description: "Yes. We help define the questions, evidence needs, and review process so the outputs are usable." },
      { title: "How do you avoid overburdening suppliers?", description: "We prioritise the suppliers and data points that matter most, use proportionate requests, and design the process to be practical for both sides." },
      { title: "Can this support EcoVadis or buyer requirements?", description: "Yes. Supplier engagement is often a critical part of broader sustainable procurement and assessment readiness." },
      { title: "Do you audit suppliers?", description: "No. We do not provide audit or assurance services." },
    ],
  },
  sustainability_strategy: {
    slug: "sustainability-strategy",
    title: "Sustainability strategy advisory",
    description: "Sustainability strategy advisory for leadership teams that need clearer priorities, a stronger operating model, and a practical route from ambition to governed execution.",
    heroAlt: "Sustainability strategy advisory for leadership planning and governance",
    introHeading: "Turn sustainability ambition into a strategy that teams can actually run",
    introParagraphs: [
      "Sustainability strategy often fails in two ways. It stays too abstract to guide decisions, or it becomes a list of disconnected initiatives without ownership, governance or measurable progress.",
      "We help leadership teams define the priorities, operating model, and execution path that connect sustainability ambition to real programmes, decisions and reporting.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/outsourced-sustainability-management", label: "Outsourced sustainability management" },
      { href: "/services/esg-advisory/sustainability-training", label: "Sustainability training" },
      { href: "/services/esg-advisory/net-zero-and-decarbonisation", label: "Net zero and decarbonisation" },
    ],
    coverageIntro: "We work on strategy that can support leadership choices, cross-functional alignment, and delivery governance.",
    deliverables: [
      { title: "Current-state review", description: "Assess material issues, stakeholder pressures, reporting requirements, and current programme maturity." },
      { title: "Priority setting", description: "Define what the organisation should focus on first, what can wait, and how ambition translates into decisions." },
      { title: "Target operating model", description: "Clarify ownership, governance, decision rights, and the functions needed to support execution." },
      { title: "Roadmap and initiative design", description: "Structure the strategic priorities into workstreams, dependencies and measurable milestones." },
      { title: "Leadership and board framing", description: "Present the strategy in language that supports executive decision-making and accountability." },
      { title: "Execution governance", description: "Set the review cadence, progress tracking, and change-control logic needed to keep the strategy active." },
    ],
    bestFitIntro: "This service is most valuable when leadership wants direction, but the current sustainability work is fragmented or underpowered.",
    bestFit: [
      { title: "Before scaling the programme", description: "You need a clear strategy before investing further in reporting, systems, targets or headcount." },
      { title: "After reactive compliance work", description: "The organisation has been responding to requests case by case and now needs a more integrated direction." },
      { title: "When ownership is unclear", description: "Teams are active, but there is no agreed operating model, prioritisation logic, or leadership view of progress." },
    ],
    workflowIntro: "We help leadership move from broad intent to a strategy with owners, workstreams and review cadence.",
    workflow: [
      { title: "Clarify", description: "Review pressures, stakeholder needs, and the current programme shape." },
      { title: "Prioritise", description: "Decide what matters most and how the strategy should be framed." },
      { title: "Structure", description: "Define the operating model, roadmap and accountability design." },
      { title: "Activate", description: "Support leadership communication, workstream mobilisation, and review governance." },
    ],
    serviceTypes: [
      "Sustainability strategy development",
      "ESG operating model design",
      "Leadership strategy support",
      "Roadmap development",
      "Governance design",
      "Strategy activation support",
    ],
    faq: [
      { title: "What is included in sustainability strategy advisory?", description: "It includes current-state review, priority setting, operating model design, roadmap creation, executive framing, and execution governance." },
      { title: "How is this different from reporting support?", description: "Reporting support focuses on disclosure readiness and evidence. Sustainability strategy focuses on the broader direction, priorities, operating model, and delivery path behind the programme." },
      { title: "Do you work with leadership teams directly?", description: "Yes. This work is most effective when leadership is involved in the priority and governance decisions, not only informed after the fact." },
      { title: "Can this include climate, supply chain, and people topics together?", description: "Yes. The strategy should reflect the organisation's real material issues and stakeholder pressures, not treat sustainability as a single-topic programme." },
      { title: "Do you also help implement the strategy?", description: "Yes. Our model is advisory plus implementation, so we can support governance, workstream setup, and operating discipline after the strategy is agreed." },
      { title: "Is this relevant for mid-market firms?", description: "Yes. Mid-market organisations often need strategy work precisely because sustainability responsibilities are spread thinly and priorities need sharper focus." },
      { title: "Do you set public commitments for us?", description: "We can support the thinking and governance behind commitments, but public commitments need to reflect your organisation's actual readiness and decisions." },
    ],
  },
  sustainability_training: {
    slug: "sustainability-training",
    title: "Sustainability training and enablement",
    description: "Sustainability training and enablement for organisations that need shared understanding, better decision quality, and stronger execution across leadership, functional teams, and programme owners.",
    heroAlt: "Sustainability training and enablement for leadership and teams",
    introHeading: "Build the internal understanding needed to make sustainability work stick",
    introParagraphs: [
      "Programmes slow down when only a small group understands the requirements, while the teams expected to provide data, evidence or operational changes are left unsure what good looks like.",
      "We design sustainability training and enablement that is grounded in your actual reporting needs, operating model, and decision points so teams can contribute with more confidence and less confusion.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/sustainability-strategy", label: "Sustainability strategy" },
      { href: "/services/esg-advisory/ecovadis-readiness", label: "EcoVadis readiness" },
      { href: "/services/esg-advisory/outsourced-sustainability-management", label: "Outsourced sustainability management" },
    ],
    coverageIntro: "We focus on training that improves execution quality, not generic awareness sessions.",
    deliverables: [
      { title: "Audience and needs analysis", description: "Define which teams need what level of understanding, from leadership framing to operational execution guidance." },
      { title: "Tailored content design", description: "Create sessions aligned to your reporting requirements, governance model, and business context." },
      { title: "Role-based training delivery", description: "Run targeted sessions for leadership, procurement, HR, operations, finance, marketing or programme teams as needed." },
      { title: "Practical playbooks and guides", description: "Provide usable materials that teams can reference during reporting cycles and programme work." },
      { title: "Capability gap identification", description: "Highlight where further process, policy or system support is needed beyond training." },
      { title: "Enablement roadmap", description: "Define how learning, ownership and reinforcement will continue after the initial sessions." },
    ],
    bestFitIntro: "This service is most valuable when knowledge gaps are affecting data quality, ownership or programme momentum.",
    bestFit: [
      { title: "During programme rollout", description: "New requirements are being introduced and teams need practical guidance on their role in delivery." },
      { title: "Before a reporting cycle", description: "Contributors need a clearer view of expectations, evidence quality, and deadlines." },
      { title: "After repeated confusion", description: "The same misunderstandings keep surfacing across functions, slowing progress and weakening outputs." },
    ],
    workflowIntro: "We tie the training to your actual operating model so the sessions produce better execution, not only awareness.",
    workflow: [
      { title: "Assess", description: "Identify audiences, recurring gaps, and the decisions or activities that need better support." },
      { title: "Design", description: "Build tailored content, examples and session formats." },
      { title: "Deliver", description: "Run the sessions and provide supporting materials." },
      { title: "Reinforce", description: "Highlight next steps for capability development, governance and ongoing enablement." },
    ],
    serviceTypes: [
      "Sustainability training",
      "ESG enablement",
      "Role-based capability building",
      "Reporting contributor training",
      "Leadership sustainability workshops",
      "Operational playbook development",
    ],
    faq: [
      { title: "What does sustainability training and enablement include?", description: "It includes audience analysis, tailored session design, delivery, supporting materials, and a follow-on plan for reinforcement and capability building." },
      { title: "Is the training generic or tailored?", description: "It is tailored. We align the sessions to your reporting needs, operating model, and the teams who need to act on the content." },
      { title: "Who is this usually for?", description: "It can be designed for leadership, sustainability teams, procurement, finance, HR, operations, product teams, or broader contributor groups depending on the need." },
      { title: "Can this support specific frameworks?", description: "Yes. Training can be shaped around the frameworks, assessments and reporting expectations relevant to your organisation." },
      { title: "Do you provide workshop materials too?", description: "Yes. We can provide practical materials such as checklists, role guides, and reference documents for teams to use after the sessions." },
      { title: "How do we know training is the right answer?", description: "We assess whether the real issue is knowledge, process design, ownership or systems. Sometimes training is enough, and sometimes it needs to be paired with broader operating model changes." },
      { title: "Do you offer off-the-shelf certification courses?", description: "No. Our focus is tailored enablement linked to your organisation's actual sustainability work." },
    ],
  },
  outsourced_sustainability_management: {
    slug: "outsourced-sustainability-management",
    title: "Outsourced sustainability management",
    description: "Outsourced sustainability management for organisations that need sustained ESG leadership capacity, programme coordination, and governance support without building a full in-house team immediately.",
    heroAlt: "Outsourced sustainability management for programme coordination and leadership capacity",
    introHeading: "Add sustainability capacity without waiting to build the full internal team",
    introParagraphs: [
      "Many organisations know sustainability work matters, but they do not yet have the internal capacity to coordinate strategy, reporting, supplier requests, stakeholder communication, and programme governance at the level required.",
      "Our outsourced sustainability management offer provides structured support to keep the programme moving, with advisory plus implementation discipline rather than ad hoc task support.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/sustainability-strategy", label: "Sustainability strategy" },
      { href: "/services/esg-advisory/sustainability-training", label: "Sustainability training" },
      { href: "/services/esg-advisory/rfp-tender-support", label: "RFP and tender support" },
    ],
    coverageIntro: "We provide programme capacity with governance, prioritisation and execution support built in.",
    deliverables: [
      { title: "Programme coordination", description: "Keep workstreams moving across reporting, policy, supplier engagement, data requests, and stakeholder needs." },
      { title: "Leadership support", description: "Provide structured updates, issue visibility, and recommendations for decision-makers." },
      { title: "Calendar and cadence management", description: "Run the routines, follow-ups, and review points needed to keep the programme from drifting." },
      { title: "Cross-functional orchestration", description: "Coordinate contributors across procurement, operations, HR, finance, marketing and leadership." },
      { title: "Documentation and evidence control", description: "Support policy, evidence and reporting materials so work is more organised and repeatable." },
      { title: "Capability transition planning", description: "Help define what should remain outsourced, what should be handed over, and what internal capability needs to be built next." },
    ],
    bestFitIntro: "This service is most useful when sustainability needs consistent management attention, but dedicated internal capacity is still limited.",
    bestFit: [
      { title: "No full-time sustainability lead yet", description: "The organisation needs structured support now rather than waiting to make the perfect hire." },
      { title: "Workstreams are multiplying", description: "Reporting, customer requests, supplier work, and internal initiatives are competing for limited bandwidth." },
      { title: "Leadership needs visibility", description: "Executives need clearer tracking, ownership and escalation than the current informal setup provides." },
    ],
    workflowIntro: "We step in as a governed delivery layer, not a vague extra pair of hands.",
    workflow: [
      { title: "Stabilise", description: "Review current obligations, active workstreams, and immediate pressure points." },
      { title: "Structure", description: "Set priorities, working cadence, roles and decision forums." },
      { title: "Coordinate", description: "Run the day-to-day programme rhythm across teams and topics." },
      { title: "Transition", description: "Define the long-term operating model, including internal capability build where needed." },
    ],
    serviceTypes: [
      "Outsourced sustainability management",
      "Fractional sustainability programme support",
      "ESG programme coordination",
      "Cross-functional sustainability governance",
      "Leadership reporting support",
      "Capability transition planning",
    ],
    faq: [
      { title: "What is outsourced sustainability management?", description: "It is structured external support to coordinate sustainability strategy, reporting, governance and related workstreams when internal capacity is limited." },
      { title: "Is this a fractional leadership model?", description: "It can operate like a fractional programme lead, but with a stronger delivery and governance focus across the full workstream." },
      { title: "How is this different from one-off advisory?", description: "One-off advisory solves a defined problem. Outsourced sustainability management provides ongoing coordination, accountability and progress management across multiple topics." },
      { title: "Can this work alongside internal sustainability staff?", description: "Yes. It can support an existing lead, fill temporary gaps, or help scale the programme while internal capability is still developing." },
      { title: "What kind of organisations use this?", description: "It is useful for growing mid-market firms, companies under increasing customer or reporting pressure, and leadership teams that need more structured execution without adding a full team immediately." },
      { title: "Do you take ownership away from internal teams?", description: "No. We help clarify internal ownership and keep work moving. The model should strengthen accountability, not obscure it." },
      { title: "Can this later transition in-house?", description: "Yes. We can help define the handover path, internal roles, and capability needs for a later transition." },
    ],
  },
  rfp_tender_support: {
    slug: "rfp-tender-support",
    title: "RFP and tender sustainability support",
    description: "RFP and tender sustainability support for organisations that need stronger responses to buyer sustainability requirements, clearer evidence, and a repeatable way to answer ESG questions under commercial deadlines.",
    heroAlt: "RFP and tender sustainability support for bid responses and buyer requirements",
    introHeading: "Respond to buyer sustainability questions with more confidence and less scrambling",
    introParagraphs: [
      "Commercial teams are increasingly asked to answer detailed sustainability questions in RFPs and tenders, but the evidence often sits across procurement, HR, operations, sustainability and leadership teams.",
      "We help organisations improve the quality, consistency and repeatability of tender responses so buyer expectations can be met without rebuilding the answer from scratch each time.",
    ],
    introLinks: [
      { href: "/services/esg-advisory/ecovadis-readiness", label: "EcoVadis readiness" },
      { href: "/services/esg-advisory/supplier-engagement", label: "Supplier engagement" },
      { href: "/services/esg-advisory/outsourced-sustainability-management", label: "Outsourced sustainability management" },
    ],
    coverageIntro: "We focus on the evidence base, response process, and operating model behind stronger commercial responses.",
    deliverables: [
      { title: "Requirement review", description: "Assess the sustainability questions buyers are asking and identify where evidence is strong, weak or missing." },
      { title: "Response library design", description: "Create reusable answer banks, evidence packs, and supporting materials for common sustainability topics." },
      { title: "Cross-functional answer process", description: "Define how sales, bid, sustainability, HR, procurement and operations teams contribute under time pressure." },
      { title: "Evidence strengthening", description: "Improve the documentation and data needed to support recurring buyer questions." },
      { title: "Bid-specific response support", description: "Support live opportunities where sustainability content needs to be shaped, reviewed or strengthened." },
      { title: "Improvement roadmap", description: "Use tender feedback and recurring gaps to strengthen the programme and future responses." },
    ],
    bestFitIntro: "This service is most useful when sustainability questions are affecting win rates or consuming too much commercial effort.",
    bestFit: [
      { title: "Frequent buyer questionnaires", description: "The same sustainability questions keep coming back, but answers are inconsistent or slow to prepare." },
      { title: "Growing enterprise sales motion", description: "Sales teams need stronger support as procurement-led ESG scrutiny increases." },
      { title: "Evidence gaps are visible", description: "Commercial teams know what buyers are asking, but internal documentation is not yet strong enough." },
    ],
    workflowIntro: "We help create a repeatable commercial response model instead of a last-minute scramble on every bid.",
    workflow: [
      { title: "Review", description: "Analyse current tender questions, response pain points, and evidence gaps." },
      { title: "Build", description: "Create reusable materials, answer structures, and governance for response ownership." },
      { title: "Support", description: "Help shape live responses where the stakes or complexity are higher." },
      { title: "Strengthen", description: "Use recurring requests to improve policies, evidence and future readiness." },
    ],
    serviceTypes: [
      "Tender sustainability support",
      "RFP response support",
      "Buyer questionnaire preparation",
      "Evidence pack development",
      "Commercial sustainability response library",
      "Bid governance support",
    ],
    faq: [
      { title: "What is RFP and tender sustainability support?", description: "It is support to improve how your organisation answers buyer sustainability questions through stronger evidence, reusable materials, and a clearer cross-functional response process." },
      { title: "Do you support live tenders?", description: "Yes. We can support active bid situations as well as the longer-term work needed to make future responses easier and stronger." },
      { title: "Is this only for large enterprise deals?", description: "No. It is useful whenever buyers are asking detailed sustainability questions and the organisation wants to improve response quality and efficiency." },
      { title: "Can this help improve bid consistency?", description: "Yes. A major part of the work is building reusable responses and clearer ownership so answers are more consistent across opportunities." },
      { title: "How does this connect to supplier engagement or EcoVadis?", description: "Buyer questions often touch procurement, supplier management, climate data, policies and assessments. These services can strengthen the evidence behind tender responses." },
      { title: "Do you write proposals end to end?", description: "We support the sustainability sections, evidence logic, and governance. Full proposal management can remain with your commercial or bid team." },
      { title: "Can this reveal broader sustainability gaps?", description: "Yes. Tender questions often expose where policies, data and evidence are not yet strong enough. We use that insight to define improvement priorities." },
    ],
  },
} as const satisfies Record<string, ESGServiceConfig>;

export const esgServicePathways = [
  {
    title: "Climate and carbon",
    items: [
      { href: "/services/esg-advisory/carbon-accounting", title: "Carbon accounting", description: "Emissions baseline, methodology, evidence trails, and reporting governance." },
      { href: "/services/esg-advisory/net-zero-and-decarbonisation", title: "Net zero and decarbonisation", description: "Reduction roadmap, target-setting discipline, and delivery governance." },
      { href: "/services/esg-advisory/climate-risk", title: "Climate risk", description: "Physical and transition risk assessment with disclosure-ready outputs." },
      { href: "/services/esg-advisory/cdp-reporting", title: "CDP reporting", description: "Structured response support, evidence mapping, and submission review." },
      { href: "/services/esg-advisory/product-sustainability", title: "Product sustainability", description: "Product-level sustainability analysis, claims review, and improvement priorities." },
    ],
  },
  {
    title: "Reporting and assessments",
    items: [
      { href: "/services/esg-advisory/csrd-advisory", title: "CSRD advisory", description: "Readiness, ESRS mapping, ownership, controls and evidence trails." },
      { href: "/services/esg-advisory/brsr-advisory", title: "BRSR advisory", description: "KPI mapping, data governance, and reporting workflow for India listed reporting." },
      { href: "/services/esg-advisory/uk-secr-srs-reporting", title: "UK SECR and SRS reporting", description: "Methodology, data quality, governance and board-ready climate reporting." },
      { href: "/services/esg-advisory/ecovadis-readiness", title: "EcoVadis readiness", description: "Gap assessment, policy review, evidence mapping, and submission support." },
      { href: "/services/esg-advisory/b-corp-certification", title: "B Corp certification", description: "Readiness planning, evidence coordination, and certification support." },
      { href: "/services/esg-advisory/supplier-engagement", title: "Supplier engagement", description: "Sustainable procurement support and value chain data improvement." },
    ],
  },
  {
    title: "Strategy and execution support",
    items: [
      { href: "/services/esg-advisory/sustainability-strategy", title: "Sustainability strategy", description: "Priority setting, operating model design, and roadmap development." },
      { href: "/services/esg-advisory/sustainability-training", title: "Sustainability training", description: "Role-based enablement, playbooks and contributor capability building." },
      { href: "/services/esg-advisory/outsourced-sustainability-management", title: "Outsourced sustainability management", description: "Ongoing programme coordination and leadership support." },
      { href: "/services/esg-advisory/rfp-tender-support", title: "RFP and tender support", description: "Buyer questionnaire support, evidence packs, and reusable response libraries." },
    ],
  },
] as const;
